// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2oLmnN289kKfwHwbNdp0a4cv4L5-nXng',
    appId: '1:439722045400:web:ba98e9b8cb1aa2c5958cad',
    messagingSenderId: '439722045400',
    projectId: 'bungeeqr',
    authDomain: 'bungeeqr.firebaseapp.com',
    storageBucket: 'bungeeqr.appspot.com',
    measurementId: 'G-95JZ99Q893',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsOBNZ5BT0Cp5B6f5hN_IlSY7rmlxSQjQ',
    appId: '1:439722045400:android:92d58be5a155728f958cad',
    messagingSenderId: '439722045400',
    projectId: 'bungeeqr',
    storageBucket: 'bungeeqr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdT3qwtYysOad5uyqQKXybt2yK1JMRNLc',
    appId: '1:439722045400:ios:9f5d4500573b32cc958cad',
    messagingSenderId: '439722045400',
    projectId: 'bungeeqr',
    storageBucket: 'bungeeqr.appspot.com',
    iosClientId: '439722045400-hs6dg0hfi5936lmq251e9q3m71mku2lp.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdT3qwtYysOad5uyqQKXybt2yK1JMRNLc',
    appId: '1:439722045400:ios:834fb68893be06b0958cad',
    messagingSenderId: '439722045400',
    projectId: 'bungeeqr',
    storageBucket: 'bungeeqr.appspot.com',
    iosClientId: '439722045400-enq77cmpl4vfgoqurfp96nth6dk27kva.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMovil.RunnerTests',
  );
}
